### ISSUE TITLE
TypeError: parse() got an unexpected keyword argument 'type_comments' (ast.parse)

### ISSUE THREAD

**Issue by jhbuhrman** [ilevkivskyi/com2ann#26]
```
> python -VV
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]

> poetry add --dev com2ann
Using version ^0.1.1 for com2ann

Updating dependencies
Resolving dependencies...

Writing lock file


Package operations: 1 install, 0 updates, 0 removals

  - Installing com2ann (0.1.1)

> com2ann tests\conftest.py
File: tests\conftest.py
INTERNAL ERROR while processing tests\conftest.py
Please report bug at https://github.com/ilevkivskyi/com2ann/issues
Traceback (most recent call last):
  File "d:\dev\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\dev\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\...\venv\Scripts\com2ann.exe\__main__.py", line 7, in <module>
  File "d:\...\venv\lib\site-packages\com2ann.py", line 877, in main
    translate_file(args.infile, args.outfile, options)
  File "d:\...\venv\lib\site-packages\com2ann.py", line 819, in translate_file
    python_minor_version=options.python_minor_version)
  File "d:\...\venv\lib\site-packages\com2ann.py", line 772, in com2ann
    feature_version=python_minor_version)
TypeError: parse() got an unexpected keyword argument 'type_comments'

>
```
It happens when `ast.parse(...)` is being called with the `type_comments` kwarg. `ast.py` is at `D:\dev\Python37\Lib\ast.py`.

**Comment by jhbuhrman** [comment]
I see already:

> The tool requires Python 3.8 to run

Sorry!
