### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement com2amm (from versions: none)

### ISSUE THREAD

**Issue by sebastian-philipp** [ilevkivskyi/com2ann#32]
```
pip install -v  com2amm                        
Using pip 20.2.1 from /home/sebastian/Repos/ceph/src/pybind/mgr/venv38/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-yrrlga4n
Created temporary directory: /tmp/pip-req-tracker-p88wxv0i
Initialized build tracking at /tmp/pip-req-tracker-p88wxv0i
Created build tracker: /tmp/pip-req-tracker-p88wxv0i
Entered build tracker: /tmp/pip-req-tracker-p88wxv0i
Created temporary directory: /tmp/pip-install-2skuyzet
1 location(s) to search for versions of com2amm:
* https://pypi.org/simple/com2amm/
Fetching project page and analyzing links: https://pypi.org/simple/com2amm/
Getting page https://pypi.org/simple/com2amm/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/com2amm/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/com2amm/ HTTP/1.1" 404 13
Status code 404 not in (200, 203, 300, 301)
Could not fetch URL https://pypi.org/simple/com2amm/: 404 Client Error: Not Found for url: https://pypi.org/simple/com2amm/ - skipping
Given no hashes to check 0 links for project 'com2amm': discarding no candidates
ERROR: Could not find a version that satisfies the requirement com2amm (from versions: none)
ERROR: No matching distribution found for com2amm
Exception information:
Traceback (most recent call last):
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/venv38/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/venv38/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/venv38/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 324, in run
    requirement_set = resolver.resolve(
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/venv38/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/venv38/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/venv38/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 339, in _get_abstract_dist_for
    self._populate_link(req)
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/venv38/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _populate_link
    req.link = self._find_requirement_link(req)
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/venv38/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 270, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/venv38/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 926, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for com2amm
Removed build tracker: '/tmp/pip-req-tracker-p88wxv0i'

```

```
$ pip --version
pip 20.2.1 from /home/sebastian/Repos/ceph/src/pybind/mgr/venv38/lib/python3.8/site-packages/pip (python 3.8)
```

Looks like pip needs some new mandatory information? Might be related to https://pip.pypa.io/en/stable/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020

**Comment by sebastian-philipp** [comment]
sigh. `pip install com2ann` worked. Would be great to have a better error message for those kind of errors.
